.github/workflows/node.js.yml
ID number:
Branch name:
Description:
Contributors:
=> :construction_worker: Create node.js.yml

package.json, postcss.config.js, src/index.css, src/pages/StudentDashboard/StudentDashboard.js, tailwind.config.js, yarn.lock
ID number: 4 
Branch name: add-tailwind
Description: added tailwind and the flowbite library along with their configs
Link to ticket: https://www.notion.so/2022-Charlie-Internship-e17fc9562522490392be1f70577b3900?p=7cdbcdf062be45e48e97046e13fbc1e4&pm=s
Notes for the reviewer: can import any react-flowbite component
Contributors: Logan Ramos, Jorge Linares
=> added tailwind and flowbite along with their configs

src/userMock.js
ID number: 2
Branch name: react-mock-data
Description: Created a single user with nested objects to simulate JSON payload from fetch request. User -> Student -> Assessments
Link to ticket: https://www.notion.so/387c6c59e77e4636a19a132718d96e0b?v=7caf5bf3b5d64169bb6a5c6d7597892e&p=0d3b71979c3d46199f9e18b38155494d&pm=s
Notes for the reviewer: mockUser located in src.
Contributors: Don, Sean, JB, Davon
=> completed mock data

.eslintrc.yml, .github/workflows/lint.yml, package.json, src/App.js, src/App.test.js, src/index.js, src/pages/StudentDashboard/StudentDashboard.js, src/pages/StudentDashboard/StudentDashboard.test.js, src/reportWebVitals.js, src/setupTests.js, yarn.lock
ID number: 6
Branch name: linter-config
Description: Added eslint and github actions with configurations
Link to ticket: https://www.notion.so/Student-Application-Dashboard-1333c4b5cd684d179b86f03fc61cab4f?p=241386e0db9c45fc9afea4b32cdebf20&pm=s
Contributors: JB, Logan, Davon, Don, Sean, Jorge, Sarah
=> Linter config

.eslintrc.yml, package.json, src/components/Assessment.js, src/components/Assessment.test.js, src/pages/StudentDashboard/StudentDashboard.js, src/userMock.js, yarn.lock
ID number: 9
Branch name: assessment
Description: created assessment component that can take in user data and render a page with 6 weeks worth of assessments and attached information.
Link to ticket: https://www.notion.so/2022-Charlie-Internship-e17fc9562522490392be1f70577b3900?p=070a6c15a623412e956b66819c60d4bd&pm=s
Contributors: Don Yoon
=> Assessment

src/components/Header.js, src/components/Navigation.js, src/components/Navigation.test.js
ID number: 7
Branch name: react-navigation
Description: added navigation component and testing
Link to ticket: https://www.notion.so/2022-Charlie-Internship-e17fc9562522490392be1f70577b3900?p=c8c3f4d0a4a64ee4b7f9684cca9673b2&pm=s
Notes for the reviewer: added navigation component and testing
Contributors: Jorge, Logan, JB, Don, Davon
=> added navigation component and navigation testing

public/index.html, public/manifest.json
ID number: 10
Branch name: logo-bug
Description: Fixed error showing on page inspection due to incorrect reference of non existent icon asset
Link to ticket: https://www.notion.so/Student-Application-Dashboard-1333c4b5cd684d179b86f03fc61cab4f?p=055942c0ada24e4fb2f6f5b9bb6625fa&pm=s
Contributors: Don
=> removed incorrect references for non existent icons in manifest

src/components/AttendancePolicyModal.js, src/components/PolicyModal.js, src/components/PolicyModal.test.js, src/pages/StudentDashboard/StudentDashboard.js
ID number: 8
Branch name: react-modals
Description: "Added Policy Modals and testing"
Link to ticket:[
](https://www.notion.so/2022-Charlie-Internship-e17fc9562522490392be1f70577b3900?p=11ef786c82b9448988efae63f7b9f336&pm=s)
Contributors: Davon, Jorge, Don,JB, Logan, Sean
=> React modals

src/components/Greeter.js
ID number: 19
Branch name: Styling Greeting
Description: Added some styling to the greeting
Link to ticket: https://www.notion.so/2022-Charlie-Internship-e17fc9562522490392be1f70577b3900?p=491b2bc19f324284bf106c3b4f7c9980&pm=s
Contributors: JB, Don, Logan, Jorge, Sean, Devon
=> added some styling to the greeting

src/components/Absences.js
ID number: 18
Branch name: absences-styling
Description: Added styling to absences
Link to ticket: [
](https://www.notion.so/React-Styling-Absences-6facf01792b14ade9aecbc0868d04e37)
Notes for the reviewer: 
Contributors: Sean
=> styling changes made to absences

src/components/Assessment.js, src/components/Assessment.test.js, src/components/Navigation.test.js, src/userMock.js, tailwind.config.js
ID number: 13
Branch name: assessment-styling
Description: finished dynamic styling for all rendered divs for each week as well as ensuring that the codebase will still work for incoming data structure. Implemented react testing library to test functional component.
Link to ticket: https://www.notion.so/2022-Charlie-Internship-e17fc9562522490392be1f70577b3900?p=32edd4cf1b2c44e0845c0d66c8dd819b&pm=s
Notes for the reviewer: testing made fun, courtesy of @testing-library/react
Contributors: Don, Logan, Sean, JB, Jorge, Davon
=> Assessment styling

src/components/Header.js, src/components/Navigation.js, src/components/Navigation.test.js
ID number: 16
Branch name: header-styling
Description: Header and nav button styling
Link to ticket: https://www.notion.so/2022-Charlie-Internship-e17fc9562522490392be1f70577b3900?p=1b8287c985f547d2a1641cf51cfb304a&pm=s
Contributors: Jorge, Sean, JB, Davon, Logan, Don
=> syled header and navigation button

src/components/Assessment.js, src/userMock.js
ID number: 22
Branch name: user-mock-fix
Description: update mock data to match incoming data structure. Fix assessment component colorchange function to match incoming data structure.
Link to ticket:  https://www.notion.so/2022-Charlie-Internship-e17fc9562522490392be1f70577b3900?p=5e2ae8bc322043d986f93b481916fc78&pm=s
Contributors: Don
=> fixed mock user data and updated component to match incoming data type

src/components/Button.js
ID number: 21
Branch name: button-styling
Description: Added custom button component that can take dynamic text and onClick
Link to ticket: https://www.notion.so/3c617b3aba60438ea07f6065f97dafb4?v=ed93b67784f4486eaad077353b10faca&p=33a82f88c2824b12bd4a242aa6e59468&pm=s
Notes for the reviewer: Adding the buttons to the app in a different ticket
Contributors: Logan, Sean, Jorge
=> added custom button component

src/components/Button.js, src/components/Header.js, src/components/Navigation.js
ID number: 23
Branch name: header-styling-update
Description: Updated the header styling and added custom button
Link to ticket: https://www.notion.so/3c617b3aba60438ea07f6065f97dafb4?v=ed93b67784f4486eaad077353b10faca&p=989b306370c24e70a6dd190c7aa9a3fa&pm=s
Contributors: Logan, Jorge, Sean
=> updated header styling with button

src/components/Navigation.test.js, src/components/PolicyModal.js
ID number: 17
Branch name: modal-styling
Description: text content formatting and adding content y axis scrollbar
Link to ticket: https://www.notion.so/2022-Charlie-Internship-e17fc9562522490392be1f70577b3900?p=b1bc4bebf17f4340afd48cf77ff223a8&pm=s
Contributors: Davon, JB, Don
=> Modal styling

src/components/PolicyModal.js
ID number: 24
Branch name: update-buttons
Description: Changed from flowbite buttons to custom button component
Link to ticket: https://www.notion.so/3c617b3aba60438ea07f6065f97dafb4?v=ed93b67784f4486eaad077353b10faca&p=90ba0c17158b4fa78f807b2d6a66d3ca&pm=s
Notes for the reviewer: 
Contributors: Logan, Sean, Jorge
=> changed all buttons to custom buttons

src/pages/StudentDashboard/StudentDashboard.js
ID number: 27
Branch name: comp-component
Description: moved comprehension component above weekly assessment component
Link to ticket: https://www.notion.so/2022-Charlie-Internship-e17fc9562522490392be1f70577b3900?p=9439829987c341eebc92bed8628741f5&pm=s
Contributors: Don
=> moved comprehension component placement on student dashboard

.github/workflows/lint.yml, src/components/Absences.js, src/components/Absences.test.js, src/components/Assessment.js, src/components/Button.js, src/components/Greeter.js, src/components/Header.js, src/components/Navigation.js, src/components/PolicyModal.js, src/index.css, src/pages/StudentDashboard/StudentDashboard.js, src/userMock.js, tailwind.config.js
ID number: 15
Branch name: student-dashboard-styling
Description: Styled the student dashboard
Link to ticket: https://www.notion.so/Student-Application-Dashboard-1333c4b5cd684d179b86f03fc61cab4f?p=b1c19c75d89446f782d0063d780d1512&pm=s
Contributors: Sean, JB, Logan, Davon, Jorge, Don
=> Student dashboard styling

src/components/Assessment.js
ID number: 26
Branch name: status-colors
Description: "Changed Colors"
Link to ticket: 26
Contributors: Davon, Don, Jorge, Logan, Sean
=> changed colors

README.md
ID number:
Branch name:
Description:
Notes for the reviewer: My linter added some additional spaces in the README
Contributors: Sarah
=> :memo: adds live link to the README for quick reference

src/components/Absences.js, src/components/Assessment.js, src/index.css, src/pages/StudentDashboard/StudentDashboard.js, tailwind.config.js
ID number: [52]
Branch name: body-styles
Description: Added background color to page as 'neutral-200', added LEARN font to whole page, used sizing scale to adjust headings/text, and justified notes to 80 characters wide.
Link to ticket: https://www.notion.so/2022-Delta-Internship-6af24e8d3bb349ea8fe44f3d6351f036?p=380515fd1e444efaae2095ad0d3e5586&pm=s
Notes for the reviewer: We both found a deeper connection with Tailwind CSS by taking this ticket first and working through it together.
Contributors: Nicole and Will
=> 💄 Adds or fixes UI, Ticket ID:[52],React: BodyStyles

src/App.js, src/components/Header.js, src/pages/StudentLogin/StudentLogin.js, src/pages/StudentLogin/StudentLogin.test.js
ID number: [54]
Branch name: student-login-page
Description: Created a Student login page styled to match the header, added header to page, and created a student login in test page with passing tests.
Link to ticket: https://www.notion.so/2022-Delta-Internship-6af24e8d3bb349ea8fe44f3d6351f036?p=8f36191dfc6045409e2bf15aa243c713&pm=s
Contributors:
=> Student login page

package.json, src/App.js, src/App.test.js, src/pages/StudentDashboard/StudentDashboard.js, yarn.lock
ID number: [55]
Branch name: Router
Description: Added React router DOM to application and verified it with /login in the browser.
Link to ticket: https://www.notion.so/2022-Delta-Internship-6af24e8d3bb349ea8fe44f3d6351f036?p=046fab29a689468eabb530d34ecd3fe6&pm=s
Contributors: Don, Logan, Nicole, Will, Ahmed, Luis, and Gene
=> React: Router, [55], added React router and verified deployment

src/components/PolicyModal.js
ID number: 57
Branch name: modal-font
Description: Update the font in the modal to be the same as the rest of the page
Link to ticket: https://www.notion.so/Student-Application-Dashboard-1333c4b5cd684d179b86f03fc61cab4f?p=91b34570c4f2406a9be31751fbecbce2&pm=c
Contributors: Luis, Gene, Will, Nicole, Ahmed
=> Updated font to be the same as the rest of page

src/App.js, src/App.test.js, src/components/Button.js, src/components/Header.js, src/components/Navigation.js, src/components/Navigation.test.js, src/index.js, src/pages/StudentDashboard/StudentDashboard.js, src/pages/StudentLogin/StudentLogin.js
ID number: [56]
Branch name: navigation
Description: Added route to login page, user is only able to see student dashboard when logged in
Link to ticket: https://www.notion.so/2022-Delta-Internship-6af24e8d3bb349ea8fe44f3d6351f036?p=29175f619fde465a8157b48b1364b2fe&pm=s
Notes for the reviewer: Logan and Don save the day
Contributors: Luis, Nicole, Will, Ahmed, Gene, Don, and Logan
=> Navigation

.github/workflows/accessibility-validation.yml
ID number: 58
Branch name: accessibility-validations
Description: - Add GitHub Actions workflow for accessibility auditing. Check all color contrasts.
Link to ticket: https://www.notion.so/Student-Application-Dashboard-1333c4b5cd684d179b86f03fc61cab4f?p=c4613c2e8c894d2e8c86f9c5ee6da2bd&pm=c
Notes for the reviewer: After running the Action in GitHub it was found that quite a few color contrasts were failing. We need a new ticket to have everyone come together to choose some different colors. 
Contributors: Luis, Nicole, Will
=> added accessibility validations to student

src/components/Button.js, src/pages/StudentLogin/StudentLogin.js, tailwind.config.js
ID number: [64]
Branch name: color-contrast
Description: Learn purple previously assigned to the login button in the header, and the font color on the login page was failing contrast scores. Implemented the suggested colors the accessibility auditor suggested.
Link to ticket: https://www.notion.so/2022-Delta-Internship-6af24e8d3bb349ea8fe44f3d6351f036?p=fef0f173aa2b43269a631c2c241f0318&pm=s
Contributors: Nicole
=> 💄 React: Color Contrast [64] color contrast flags have been corrected

package.json, src/App.js, src/components/Assessment.js, src/components/Attendance.js, src/components/Greeter.js, src/components/Header.js, src/components/Header.test.js, src/components/Navigation.js, src/index.css, src/pages/StudentDashboard/StudentDashboard.js, src/pages/StudentLogin/StudentLogin.js, src/userMock.js, tailwind.config.js, yarn.lock
ID number: 65
Branch name: mobile-view
Description: Worked on styling to optimize app functionality on mobile devices 
Link to ticket: https://www.notion.so/2022-Delta-Internship-6af24e8d3bb349ea8fe44f3d6351f036?p=79ba54d3e1474a3eb11fe98823e912bb&pm=s
Contributors: Luis, Will, Nicole, and Gene
=> 💄 [65] Mobile view

src/pages/StudentDashboard/StudentDashboard.js
ID number: [83]
Branch name: absence-session
Description: The absence section is aligned.
Link to ticket: https://www.notion.so/2022-Echo-Internship-07a11d3d30da40098b4ec56c93419db0?p=9b7b77b9423c432abdf16b824c5e5cc5&pm=s
Contributors: Gene and Jason
=> 💄Aligned Absences section.

src/components/Absences.js, src/pages/StudentDashboard/StudentDashboard.js, src/pages/StudentLogin/StudentLogin.js
ID number: [84]
Branch name: font-color
Description: 
Link to ticket: https://www.notion.so/2022-Echo-Internship-07a11d3d30da40098b4ec56c93419db0?p=4089eccc1b874c6eba815fecb1bd21b0&pm=s
Notes for the reviewer: 
Contributors: Jason and Gene
=> 💄Changed background color and font color

src/components/Navigation.js, src/pages/StudentLogin/StudentLogin.js
ID number: 92
Branch name: cta-button
Description: all cta buttons have uniform styling.
Link to ticket: https://www.notion.so/2022-Foxtrot-Internship-37b61f8be4c648e882305901c0f16b55?p=fa41c55310844260a426af61d7642fe9&pm=s
Notes for the reviewer: cta buttons now match the LEARN academy buttons.
Contributors: Christian Macias, Nathaniel Ross-Loyo
=> button are now uniform and equivalent to the Learn academy website

src/components/AssessmentProcessModal/AssessmentProcessModal.js, src/components/AssessmentProcessModal/AssessmentProcessModal.test.js, src/pages/StudentDashboard/StudentDashboard.js
ID number: 100
Branch name: assessment-process-modal
Description: Create a new folder for AssessmentProcessModal and a js file and test file
Link to ticket: https://www.notion.so/2022-Golf-Internship-a4556022acd84408a34062ba09f9e6f8?p=2c441a8b580c4924a47351cbbf651059&pm=s
Contributors: Ramirez, Immanuel, Charlie, Sarah
=> :lipstick: created assessment process modal js and test files

src/App.js, src/pages/StudentLogin/StudentLogin.js
ID number: 104
Branch name: react-student-login
Description: Configured App.js and studentlogin.js files to no longer automatically login to webpage. Have to sign in and send the appropriate email and password to rails side to login to the home page. Recieves the created JWT token as verification and logs both the email and password.
Link to ticket: https://www.notion.so/2022-Golf-Internship-a4556022acd84408a34062ba09f9e6f8?p=aadbed9474a84919964f13b8cb2e1d71&pm=s
Notes for the reviewer: This was hard.
Contributors: Charlie, Sarah, Ramirez, Immanuel
=> ✨ :React student login

src/App.js, src/components/Header/Header.js, src/components/Navigation/Navigation.js, src/pages/StudentDashboard/StudentDashboard.js, src/pages/StudentDashboard/StudentDashboard.test.js, yarn.lock
ID number: 118
Branch name: update-login
Description: Moved useEffect to Student Dashboard and added conditional rendering
Link to ticket: 
https://www.notion.so/React-Update-login-route-flow-231e879abc3342e099b0865accce138f?pvs=4
Notes for the reviewer: N/A
Contributors: Matt, Chris, Monica, Moss
=> completed update login

src/App.test.js
ID number: 110
Branch name: app-tests-update
Description: React: Update App tests
Link to ticket: https://www.notion.so/React-Update-App-tests-af1c2d7481fb4e6ea1ec970290f5f22f?pvs=4
Contributors: Chris, Matt, Moss and Monica
=> React: Update App tests

src/pages/AboutUs/AboutUs.test.js, src/pages/CodeOfConduct/CodeOfConduct.test.js, src/pages/Contributor/Contributor.test.js, src/pages/StudentDashboard/StudentDashboard.test.js, src/pages/StudentLogin/StudentLogin.test.js, src/pages/TermsOfUse/TermsOfUse.test.js
ID number:
109
Branch name:
pages-tests
Description:
Converted pages components from enzyme to RTL
https://www.notion.so/2022-Hotel-Internship-870dd2f2a8c741a3a006a92f7a9598c9?p=29975ac0eefd4221b12b9d9951e56bf4&pm=s
Contributors:
Everyone
=> converted pages component tests to rtl

.prettierrc, tailwind.config.js
ID number:
119
Branch name:
tailwind-linting
Description:
Added prettier run file on root level
Restored tailwind config file on root level
https://www.notion.so/2022-Hotel-Internship-870dd2f2a8c741a3a006a92f7a9598c9?p=972ed75468a843059da370d6a5bd8bad&pm=s
Contributors:
Everyone
=> added prettier run file and restored tailwind config file on root level

src/pages/CodeOfConduct/CodeOfConduct.js, src/pages/CodeOfConduct/CodeOfConduct.test.js
ID number: 112
Branch name: conduct-links
Description: React: Code of Conduct links
Link to ticket: [
](https://www.notion.so/React-Code-of-Conduct-links-7db0ee73e109417ab8191c20aa5aa187?pvs=4)
Notes for the reviewer: Fixed the links on the Code of Conduct page to have working routes and the layout of the links on the page.
Contributors: Chris, Matt, Aileen, Torin, Moss and Monica
=> fixed layout and routes of links

package.json, src/App.js, src/components/Greeter/Greeter.js, src/components/Greeter/Greeter.test.js, src/components/Header/Header.js, src/pages/StudentDashboard/StudentDashboard.js, yarn.lock
ID number: 116
Branch name: student-name
Description: Added currentUser to be able to display student name on the header
Link to ticket: https://www.notion.so/React-Student-name-d28a26b4d46e4b37a1baa7c91a720de1?pvs=4
Contributors: Everyone
=> Student name

src/contributor.js
ID number:
121
Branch name:
collaborator-page
Description:
Was previously completed without bios added. This PR is just everyone's bios pasted in.
https://www.notion.so/2022-Hotel-Internship-870dd2f2a8c741a3a006a92f7a9598c9?p=4dc8cd6f15974e44b9746946a3d34e96&pm=s
Contributors:
Everyone
=> added bios to contributor page

src/components/Assessment/Assessment.js, src/components/Assessment/Assessment.test.js, src/pages/StudentDashboard/StudentDashboard.js
ID number: 123
Branch name: student-assessments
Description: made necessary changes to dynamically pass database assessment info rather than mock data
Link to ticket: https://www.notion.so/2022-Hotel-Internship-870dd2f2a8c741a3a006a92f7a9598c9?p=ff5c26ded3f14f1eb010740cde659b71&pm=s
Notes for the reviewer: N/A
Contributors: Chris, Monica, Matt, Aileen, Moss
=> made edits to pull db assessment info rather than mock data

src/pages/Contributor/Contributor.js
ID number:
Branch name:
Description:
Contributors:
=>  💄 [129] center contributor cards

src/components/Assessment/Assessment.js
ID number: 145
Branch name: status-default-value
Description: changed status value from number to string
Contributors: Manny, Ronnie, Xavier, Leo
=> 💄[145] updated status from numbers to strings

src/components/Assessment/Assessment.js
ID number: 146
Branch name: Comprehension-value
Description: updates the comprehension status of the student assessment to reflect the same as the Classroom Admin app 
Link to ticket:[
](https://www.notion.so/2023-Alpha-Internship-d8fb274ab0b24178a8493692e28821fa?p=268fcfdaab2541328f47786225e7ce4f&pm=s)
Contributors:
=> 💄[146] updates the comprehension status with same the backend

src/components/Attendance/Attendance.js, src/pages/StudentDashboard/StudentDashboard.js
ID number: 144
Branch name: absence-status-bar
Description: Colored progress bar updates with the current number of absences
Link to ticket: https://www.notion.so/2023-Alpha-Internship-d8fb274ab0b24178a8493692e28821fa?p=b732775cedbc4b5194b1722a0c1ea3c8&pm=s
Contributors: Xavier, Ronnie, Manny, Leo
=>  💄 [144] Colored progress bar updates with the current number of  absences

src/contributor.js
ID number: 150
Branch name: contributor-code-cleanup
Description: Alphabetized imports and rearranged, and organized contributors by descending cohort order(from most recent to oldest). Additionally all ids numbers were reassigned to match the descending order.
https://www.notion.so/2023-Bravo-Internship-55e260cc1a2f42538409fa514093c73b?p=3b14f5579bbd4f8fbc00dd8fd01b3c85&pm=s
Contributors:
Valeria Casillas, Evelyn Alvarez, Jose Salas
=> :technologist: Contributor's file code clean up

src/pages/Contributor/Contributor.js
ID number: 151
Branch name: order-contributors
Description: Create a function to sort through contributor's array of objects by cohort in descending order, and then by last name within each cohort. 
https://www.notion.so/2023-Bravo-Internship-55e260cc1a2f42538409fa514093c73b?p=d7d0c6f8852442d4833ae24203c00a04&pm=s
Contributors: Evelyn Alvarez, Valeria Casillas, and Jose Salas
=> :lipstick: Order of Contributors

src/components/Modals/AssessmentProcessModal/AssessmentProcessModal.js, src/components/Modals/AssessmentProcessModal/AssessmentProcessModal.test.js, src/components/Modals/ComprehensionModal/ComprehensionModal.js, src/components/Modals/ComprehensionModal/ComprehensionModal.test.js, src/components/Modals/PolicyModal/AttendancePolicyModal.js, src/components/Modals/PolicyModal/AttendancePolicyModal.test.js, src/pages/AboutUs/AboutUs.js, src/pages/CodeOfConduct/CodeOfConduct.js, src/pages/PrivacyPolicy/PrivacyPolicy.js, src/pages/StudentDashboard/StudentDashboard.js, src/pages/TermsOfUse/TermsOfUse.js, tailwind.config.js
ID number:152
Branch name: contribtuion3
Description: Configured the paragraphs in  About us, Privacy Policy, Terms of Use, Code of Conduct to have max width of 80 characters.
Link to ticket: https://www.notion.so/2023-Bravo-Internship-55e260cc1a2f42538409fa514093c73b?p=ce1a9b25db8845449a44ad3961bafca5&pm=s
Contributors: Valeria Casillas, Evelyn Alvarez, Jose Salas
=>  :lipstick: configured paragraphs to max width 80 character

src/pages/Contributor/Contributor.js, src/pages/Contributor/Contributor.test.js
ID number: 154
Branch name: contributors-test
Description: 🧹 Added test coverage for contributors bio, image, Github, LinkedIn and card.
Link to ticket: https://www.notion.so/2023-Bravo-Internship-55e260cc1a2f42538409fa514093c73b?p=0cd2186d5d324fa9bad200d93deb4ba3&pm=s
Contributors: Jose Salas, Valeria Casillas, Evelyn Alvarez
=> 🧹 [154] added test coverage to contributors page

src/components/Absences/Absences.js, src/components/Greeter/Greeter.js
ID number: 158
Branch name: mobile-greeter
Description: Mobile greeter component has been formatted to not overlap with navbar.
Link to ticket: https://www.notion.so/3c617b3aba60438ea07f6065f97dafb4?v=ed93b67784f4486eaad077353b10faca&p=328988b2a1e247e0b2337baa98091fb5&pm=s
Contributors: Valeria Casillas,Evelyn Alvarez, Jose Salas
=> :lipstick:[158] greeter component formatted.

src/components/Assessment/Assessment.test.js
ID number: 161
Branch name: assessments-testing
Description: added test coverage to the test assessment component including status, comprehension, reviewer, and notes.
Link to ticket:[
](https://www.notion.so/2023-Bravo-Internship-55e260cc1a2f42538409fa514093c73b?p=0120694c492e424aa82e41a9c38dfc2b&pm=s)
Contributors: Eddie, Evelyn, Valeria, Jose
=> 🧹 [161] added test coverage to the test assessment component

src/contributor.js, src/pages/Contributor/Contributor.test.js
ID number: 167
Branch name: react-linkedin-scraping
Description: Added other contributors About Me sections from LinkedIn data scraping
Link to ticket: https://www.notion.so/2023-Bravo-Internship-55e260cc1a2f42538409fa514093c73b?p=8d3505d6379d44b8a4c311a146be09b3&pm=s
Contributors: Valeria Casillas, Evelyn Alvarez, Jose Salas, Eddie Carrion
=> 🧹 [167] react linkedin data scraping for contributors
